# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f0d42b413b1b003a0af946f70d641d5a46475036dcfe363576f7371eeb4ae3e02c07b201093bfb06110797ddb2dc8d4e04a300754db1e1cfe2c94cb0bd86a25a

test:
  secret_key_base: 955d8b6d201d09bdc28bdea9393d997d8832a9bd1216c335d26ce750a5951d4aa7584dc249dd7f886eb7a2e72e10abbb8bf63d34464878716ce5abd4b7564a4b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
